name: WAWESOME
description: Blogging about awesome stuff.
meta_description: WAWESOME - blogging about awesome stuff.
twitter: '@wassimk'

highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: http://wassimk.github.com/
google_analytics: UA-63869523-1

# Details for the RSS feed generator
url:            wassimk.github.com
author:         Wassim Metallaoui

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
